# Generated by Django 4.1.11 on 2023-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
