# Generated by Django 4.1.11 on 2023-11-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_candidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='Candidatos',
        ),
    ]
