# Generated by Django 4.1.11 on 2023-11-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_rename_candidate_candidatos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatos',
            old_name='tituto',
            new_name='titulo',
        ),
    ]
